
---
- name: Pull and Run docker image of sportitup
  hosts: all
  tasks:
    
    - name: Remove Previous Docker Images If Exists 
      shell:
        cmd: docker rmi anshumangalav/sportitup_front  anshumangalav/sportitup_back  2> /dev/null || true
    
    - name: Pull anshumangalav/sportitup_front
      docker_image:
        name: anshumangalav/sportitup_front
        source: pull
       
    - name: Pull anshumangalav/sportitup_back
      docker_image:
        name: anshumangalav/sportitup_back
        source: pull 
    
    - name: Copy docker-compose.yml file to remote machine
      become: true
      copy: 
        src:  docker-compose.yml 
        dest: /usr/local
         
