
---
- name: Pull and Run docker image of nihar01/sportitup
  hosts: all
  tasks:
    
    - name: Remove Previous Docker Images If Exists 
      shell:
        cmd: docker rmi anshumangalav/sportitup_front  anshumangalav/sportitup_back  2> /dev/null || true
    
    - name: Pull anshumangalav/sportitup_front
      docker_image:
        name: anshumangalav/sportitup_front
        source: pull
       
    - name: Pull anshumangalav/sportitup_back
      docker_image:
        name: anshumangalav/sportitup_back
        source: pull 
    
    - name: Copy docker-compose.yml file to remote machine
      copy: 
        src:  docker-compose.yml 
        dest: /tmp/
      
   - name: Spin up application using docker-compose 
      shell:
        cmd: cd /tmp/ && docker-compose up -d     
